### ISSUE TITLE
Responsiv dizayn üçün qaynaqlar

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [CeyhunResulov/PragmatechFoundationProject#14]
Mövzu ilə bağlı aşağıdakı qaynaqları analiz edin.

- **[Birinci qaynaq](https://www.w3schools.com/css/css_rwd_mediaqueries.asp)**
- **[İkinci qaynaq](https://youtu.be/S8dQjPf0GyM)**
- **[Üçüncü qaynaq](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design)**
- **[Dördüncü qaynaq](https://www.w3schools.com/css/css_rwd_images.asp)**
- **[Beşinci qaynaq](https://www.w3schools.com/html/html_responsive.asp)**
- **[Altıncı qaynaq](https://youtu.be/zryaHix-yFA)**

**Comment by CeyhunResulov** [comment]
> Mövzu ilə bağlı bağlı qaynaqları analiz edin.
> 
> * **[birinci qaynaq](https://www.w3schools.com/css/css_rwd_mediaqueries.asp)**
> * **[ikinci qaynaq](https://youtu.be/S8dQjPf0GyM)**
> * **[Üçüncü qaynaq](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design)**
> * **[Dördüncü qaynaq](https://www.w3schools.com/css/css_rwd_images.asp)**
> * **[Beşinci qaynaq](https://www.w3schools.com/html/html_responsive.asp)**
> * **[Altıncı qaynaq](https://youtu.be/zryaHix-yFA)**

cox sagolun.
zehmet olmasa  https://github.com/CeyhunResulov/PragmatechFoundationProject/blob/master/ProjectFrontEnd/img/section3%20eskiz.png
baxarsiz sehv cekmemisem eskizi
display:grid le hazirlamaq isteyirem

**Comment by isbendiyarovanezrin** [comment]
İlk baxışdan gözümə ciddi bir səhv dəymədi.

**Comment by isbendiyarovanezrin** [comment]
Sizin mentorunuz Məhəmməddir. Zəhmət olmasa, suallarınızı ona verin. Mən sadəcə bəzən kömək etmək üçün issue'lar yazıram.
