### ISSUE TITLE
Issue'lara cavab vermək lazımdır 

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [CeyhunResulov/PragmatechFoundationProject#3]
_Issues'lərə düzgün şəkildə cavab verə bilmək üçün [bu](https://youtu.be/TKJ4RdhyB5Y) videonu izləyin, zəhmət olmasa. Videoda həm də issues'in nə olduğu və s. haqqında danışılır. İzləyin, öyrənin və bundan sonra yazılacaq issues'lərə elə cavab verin.🙂_

**Comment by CeyhunResulov** [comment]
yaxsi caliscam

**Comment by CeyhunResulov** [comment]
>

**Comment by CeyhunResulov** [comment]
> _Issues'lərə düzgün şəkildə cavab verə bilər üçün [bu](https://youtu.be/TKJ4RdhyB5Y) videonu izləyin, zəhmət olmasa. Videoda həm də məsələlər'in nə olduğu və s. haqqında danışılır. İzləyin, öyrənin və bundan sonra yazılacaq məsələlər'lərə elə cavab verin.🙂_

yaxsi. calisiram
